# Generated by Django 2.2.3 on 2019-07-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('parts', models.DecimalField(decimal_places=2, max_digits=2)),
                ('author', models.CharField(max_length=80)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blogtitle', models.CharField(max_length=80)),
                ('content', models.TextField()),
                ('partNum', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.DeleteModel(
            name='BlogArticle',
        ),
        migrations.RemoveField(
            model_name='event',
            name='img',
        ),
        migrations.AddField(
            model_name='blogpic',
            name='BlogPartNum',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=2),
        ),
    ]
