# Generated by Django 2.2.3 on 2019-07-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erc', '0002_auto_20190716_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
