# Generated by Django 2.2.3 on 2019-07-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erc', '0004_auto_20190716_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
