# Generated by Django 2.2.3 on 2019-07-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erc', '0005_auto_20190716_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
