# Generated by Django 2.2.2 on 2019-07-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erc', '0006_auto_20190716_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('post', models.CharField(max_length=80)),
                ('image', models.ImageField(blank=True, upload_to='erc/team')),
            ],
        ),
    ]
