# Generated by Django 2.2.3 on 2019-07-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erc', '0007_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='fb',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='github',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='linkedin',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, upload_to='erc/media/team'),
        ),
    ]
