# Generated by Django 2.2.2 on 2019-07-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erc', '0008_auto_20190718_0152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPic',
        ),
        migrations.AddField(
            model_name='blogpart',
            name='img',
            field=models.ImageField(blank=True, upload_to='media/blogs'),
        ),
        migrations.AlterField(
            model_name='blogpart',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.ImageField(upload_to='media/events'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/team'),
        ),
    ]
