# Generated by Django 2.2.2 on 2019-07-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erc', '0009_auto_20190718_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/newsletter')),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='parts',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='blogpart',
            name='partNum',
            field=models.IntegerField(),
        ),
    ]
