# Generated by Django 2.2.3 on 2019-07-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erc', '0011_event_filterclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/news')),
                ('date', models.DateField()),
                ('pdf', models.FileField(upload_to='')),
                ('headline', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(),
        ),
    ]
