# Generated by Django 2.2.2 on 2019-07-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erc', '0012_auto_20190720_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/erc/teams')),
                ('review', models.TextField()),
            ],
        ),
    ]
