# Generated by Django 2.2.2 on 2019-07-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erc', '0014_auto_20190721_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
