# Generated by Django 2.2.2 on 2019-07-21 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erc', '0015_auto_20190721_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date',
        ),
    ]
