# Generated by Django 2.2.3 on 2019-07-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erc', '0017_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='filterClass',
            field=models.CharField(blank=True, default='project', max_length=80),
        ),
        migrations.AlterField(
            model_name='event',
            name='problem_statement',
            field=models.FileField(blank=True, null=True, upload_to='media/events/pdf'),
        ),
    ]
