# Generated by Django 2.2.3 on 2019-07-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erc', '0019_auto_20190721_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='filterClass',
            field=models.CharField(choices=[(1, 'informative'), (2, 'tutorials'), (3, 'projects')], default=1, max_length=80),
        ),
    ]
