# Generated by Django 2.2.3 on 2019-07-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erc', '0021_auto_20190721_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='filterClass',
            field=models.CharField(choices=[('c', 'informative'), ('v', 'tutorials'), ('v', 'projects')], default='a', max_length=80),
        ),
    ]
