# Generated by Django 2.2.3 on 2019-07-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erc', '0022_auto_20190721_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='filterClass',
            field=models.CharField(choices=[('informative', 'informative'), ('tutorials', 'tutorials'), ('projects', 'projects')], default='informative', max_length=80),
        ),
    ]
